name: Tests

on: [pull_request]
permissions: read-all

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python (Latest)
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
